server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 9000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.150.48:3306/activiti-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#日志的相关配置
logging:
  level:
    root: info

